// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDhjKnkm-mSi_xziJcHyKKKZ06Rp1QtJQ',
    appId: '1:252048911743:web:d5f07cf7ef335610acfe4a',
    messagingSenderId: '252048911743',
    projectId: 'portofolio-67e9d',
    authDomain: 'portofolio-67e9d.firebaseapp.com',
    storageBucket: 'portofolio-67e9d.appspot.com',
    measurementId: 'G-3G9CQG0XQY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw6qCINIb_CbZq5ou9Vfw5jLFTmQ1lcOY',
    appId: '1:252048911743:android:19c8169b021aad92acfe4a',
    messagingSenderId: '252048911743',
    projectId: 'portofolio-67e9d',
    storageBucket: 'portofolio-67e9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDj4D7uXhVivQNzYo4zD4XeGkcqePV328',
    appId: '1:252048911743:ios:ea5bc349f53eab94acfe4a',
    messagingSenderId: '252048911743',
    projectId: 'portofolio-67e9d',
    storageBucket: 'portofolio-67e9d.appspot.com',
    iosClientId: '252048911743-s1i4ed7c2ut8bmd51omd38pnsr051un7.apps.googleusercontent.com',
    iosBundleId: 'com.example.exemploApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDj4D7uXhVivQNzYo4zD4XeGkcqePV328',
    appId: '1:252048911743:ios:ea5bc349f53eab94acfe4a',
    messagingSenderId: '252048911743',
    projectId: 'portofolio-67e9d',
    storageBucket: 'portofolio-67e9d.appspot.com',
    iosClientId: '252048911743-s1i4ed7c2ut8bmd51omd38pnsr051un7.apps.googleusercontent.com',
    iosBundleId: 'com.example.exemploApp',
  );
}
